name: Trigger Target Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - devel
    paths:
      - action/**
      - msg/**
      - srv/**

jobs:
  trigger:
    uses: Real-Move/realmove-actions/.github/workflows/reusable-trigger-target-workflow.yml@main
    with:
      repo_owner: Real-Move
      repo_name: realmove-containers
      event_type: trigger-realmove-ros2-interfaces-workflow
      branch_name: ${{ github.ref_name }} 
    secrets:
      TRIGGER_TARGET_PAT: ${{ secrets.TRIGGER_TARGET_PAT }}
